api/controllers/audio_controller.py
from flask import render_template, Response
import os
import whisper
from mtranslate import translate
from gtts import gTTS

# Obtén la ruta del directorio del script actual
current_dir = os.path.dirname(os.path.abspath(__file__))
# Combina la ruta del directorio padre con la carpeta "files"
folder_path = os.path.join(current_dir, '..', 'static', 'audios')

def audio():
    """
    Ruta para mostrar la página de audio.
    """
    return render_template('audio.html')

def upload_audio(audio_file, lang):
    """
    Ruta para manejar la carga de archivos de audio.
    """
    # Combina la ruta de la carpeta "audios" con el nombre de archivo
    save_path = os.path.join(folder_path, audio_file.filename)
    # Asegúrate de que la carpeta "audios" exista
    os.makedirs(folder_path, exist_ok=True)
    # Guarda el archivo en la ruta especificada
    audio_file.save(save_path)

    # Realiza el reconocimiento de voz y sintetización de texto a voz
    result = stt(save_path, lang)
    tts(text_to_convert=result, lang=lang, save_path=save_path)

    # Ruta para acceder al archivo de audio en la página
    audio_path = "/public/audios/" + audio_file.filename

    # Renderiza la página de visualización de audio con los resultados
    return render_template('audio_view.html', result=result, lang=lang, audio_path=audio_path)

def stt(audio_path: str, lang: str = 'it') -> str:
    """
    Convierte discurso a texto.

    Parameters
    ----------
    audio_path : str
        Ruta del archivo de audio a convertir.

    Returns
    -------
    str
        Texto convertido del discurso.
    """
    # Carga el modelo de reconocimiento de voz
    model = whisper.load_model('base')
    # Transcribe el audio utilizando el modelo
    result = model.transcribe(audio_path)

    # Extrae el texto transcrito y lo convierte a minúsculas
    input_string = result.get("text", "").lower()

    # Traduce el texto al idioma objetivo
    translated_text = translate_text(text_to_translate=input_string, lang=lang)

    return translated_text


def tts(text_to_convert: str = None, save_path: str = None, lang: str = 'it') -> None:
    """
    Convierte texto a habla y lo guarda en un archivo.

    Parameters
    ----------
    text_to_convert : str
        Texto para convertir a habla.
    save_path : str
        Ruta donde guardar el archivo de audio.
    lang : str
        Idioma del texto a convertir.

    Returns
    -------
    None
    """
    # Crea un objeto de texto a voz con el texto y el idioma especificados
    tts = gTTS(text=text_to_convert, lang=lang)

    # Guarda el resultado del texto a voz en un archivo de audio
    tts.save(save_path)

    return


def translate_text(text_to_translate: str, lang: str = 'en') -> str:
    """
    Traduce texto a otro idioma.

    Parameters
    ----------
    text_to_translate : str
        Texto para traducir.
    lang : str
        Idioma del texto a traducir.

    Returns
    -------
    str
        Texto traducido.
    """
    # Utiliza la función de traducción para obtener el texto traducido
    translated_text = translate(text_to_translate, lang)

    return translated_text

api/controllers/game_controller.py
# game_controller.py
from flask import render_template,Response
from flask_socketio import SocketIO, emit
import cv2
import mediapipe as mp
import requests
import numpy as np
import time

# Crear una instancia de SocketIO fuera de la función para que esté disponible en todo el módulo
socketio = SocketIO()

def init_socketio(app):
	# Inicializar SocketIO con la aplicación Flask
	socketio.init_app(app)

def game():
	# Renderiza la plantilla 'index.html'
	return render_template('game.html')


def video_game():
	"""
	Transmite el video en tiempo real con información de pose procesada.
	"""
	return Response(generate_frames(), mimetype='multipart/x-mixed-replace; boundary=frame')

def generate_frames():
    """
    Conecta al stream HTTP que expone el video de la cámara y procesa los frames con MediaPipe.
    """
    # URL del stream HTTP (reemplazar <host-ip> con la IP del host donde se está ejecutando el servidor Flask)
    stream_url = 'http://192.168.1.17:5001/video_feed'
    stream = requests.get(stream_url, stream=True)

    # Inicialización de MediaPipe con parámetros optimizados
    mp_pose = mp.solutions.pose
    pose = mp_pose.Pose(static_image_mode=False, min_detection_confidence=0.5, min_tracking_confidence=0.5)
    mp_drawing = mp.solutions.drawing_utils

    byte_data = b''
    for chunk in stream.iter_content(chunk_size=1024):
        byte_data += chunk
        a = byte_data.find(b'\xff\xd8')
        b = byte_data.find(b'\xff\xd9')

        if a != -1 and b != -1:
            jpg = byte_data[a:b+2]
            byte_data = byte_data[b+2:]

            # Decodificar la imagen JPEG
            image = cv2.imdecode(np.frombuffer(jpg, dtype=np.uint8), cv2.IMREAD_COLOR)

            # Reducir la resolución del frame para mejorar el rendimiento
            image = cv2.resize(image, (640, 480))  # Ajustar a 640x480 para reducir el procesamiento

            # Procesar la pose con MediaPipe
            image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
            results = pose.process(image_rgb)

            # Dibujar landmarks de la pose si están disponibles
            if results.pose_landmarks:
                mp_drawing.draw_landmarks(
                    image, results.pose_landmarks, mp_pose.POSE_CONNECTIONS)

                # Obtener coordenadas de muñecas y hombros
                right_wrist = results.pose_landmarks.landmark[mp_pose.PoseLandmark.RIGHT_WRIST]
                left_wrist = results.pose_landmarks.landmark[mp_pose.PoseLandmark.LEFT_WRIST]
                right_shoulder = results.pose_landmarks.landmark[mp_pose.PoseLandmark.RIGHT_SHOULDER]
                left_shoulder = results.pose_landmarks.landmark[mp_pose.PoseLandmark.LEFT_SHOULDER]

                # Enviar evento personalizado cuando la mano izquierda está levantada
                if left_wrist.y < left_shoulder.y:
                    print("Left hand raised - Sending custom event")
                    socketio.emit('hand_raised_event', {'left_hand_raised': True})
                if right_wrist.y < right_shoulder.y:
                    print("Right hand raised - Sending custom event")
                    socketio.emit('hand_raised_event', {'right_hand_raised': True})

            # Voltear la imagen horizontalmente
            image = cv2.flip(image, 1)

            # Codificar la imagen en formato JPEG y reducir la calidad para ahorrar ancho de banda
            _, buffer = cv2.imencode('.jpg', image, [int(cv2.IMWRITE_JPEG_QUALITY), 70])  # Reducir calidad a 70

            frame = buffer.tobytes()

            # Limitar la tasa de frames para reducir el procesamiento
            time.sleep(0.03)  # Limitar a 30 FPS

            yield (b'--frame\r\n'
                   b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n')


    # Liberar recursos al cerrar
    cap.release()

api/controllers/image_controller.py
from flask import render_template, Response, send_from_directory
import os
import gc
import math
import sys
from typing import List

import clip
import k_diffusion as K
import torch
from torch import nn
from torchvision import utils
from tqdm.notebook import tqdm

# Obtén la ruta del directorio actual del script
current_dir = os.path.dirname(os.path.abspath(__file__))
# Combina la ruta del directorio padre con la carpeta "files"
folder_path = os.path.join(current_dir, '..', 'static')

# Crea el directorio de salida si no existe
output_dir = os.path.join('static', 'images')
os.makedirs(output_dir, exist_ok=True)

from diffusion import get_model  # noqa: E402

def image():
    return render_template('image.html')

def text_to_image(prompt, steps, weight, seed):
    image_path = generate_image(prompt, steps, weight, seed)
    return render_template('image_view.html', image_path=image_path)

def move_to_folder(filename):
    return send_from_directory(folder_path, filename)

class CFGDenoiser(nn.Module):
    """
    Clase para el eliminador de ruido condicional.

    Atributos:
        inner_model (nn.Module): El modelo en el cual se realizará la eliminación de ruido.
        cond_scale (float): La escala para el modelo condicional.
    """
    def __init__(self, model: nn.Module, cond_scale: float):
        """Inicializa el eliminador de ruido condicional."""
        super().__init__()
        self.inner_model = model
        self.cond_scale = cond_scale

    def forward(self, x: torch.Tensor, sigma: torch.Tensor, clip_embed: torch.Tensor) -> torch.Tensor:
        """
        Realiza la operación de eliminación de ruido basada en el modelo interno.

        Parámetros:
            x (torch.Tensor): El tensor de entrada.
            sigma (torch.Tensor): El nivel de ruido para el modelo.
            clip_embed (torch.Tensor): Los embeddings de CLIP para la entrada.

        Retorna:
            torch.Tensor: El tensor de salida sin ruido.
        """
        x_in = torch.cat([x] * 2)
        sigma_in = torch.cat([sigma] * 2)
        clip_embed_in = torch.cat([torch.zeros_like(clip_embed), clip_embed])
        uncond, cond = self.inner_model(x_in, sigma_in, clip_embed=clip_embed_in).chunk(2)
        return uncond + (cond - uncond) * self.cond_scale

def callback(info: dict):
    """
    Función de devolución de llamada para mostrar el progreso durante el muestreo.

    Parámetros:
        info (dict): Un diccionario que contiene metadatos sobre el proceso de muestreo.
    """
    if info['i'] % 10 == 0:
        nrow = math.ceil(info['denoised'].shape[0] ** 0.5)
        grid = utils.make_grid(info['denoised'], nrow, padding=0)
        tqdm.write(f'Step {info["i"]} of 50, sigma {info["sigma"]:g}:')
        filename = os.path.join(output_dir, f'progress_step_{info["i"]}.png')
        K.utils.to_pil_image(grid).save(filename)

def generate_image(prompt: str, steps: int = 50, weight: float = 3.0, seed: int = 0) -> List[str]:
    """
    Genera imágenes basadas en un texto dado como indicación.

    Parámetros:
        prompt (str): El texto de indicación en base al cual se generarán las imágenes.
        pasos (int): El número de pasos para el proceso de muestreo.
        peso (float): El peso para la condición.
        semilla (int): La semilla aleatoria para la inicialización.

    Retorna:
        List[str]: La lista de nombres de archivo donde se guardan las imágenes generadas.
    """
    device = 'cuda' if torch.cuda.is_available() else 'cpu'

    inner_model = get_model('cc12m_1_cfg')()
    inner_model.to(device)
    _, side_y, side_x = inner_model.shape
    model_path = os.path.join('models', 'v-diffusion-pytorch', 'checkpoints', 'cc12m_1_cfg.pth')
    inner_model.load_state_dict(torch.load(model_path, map_location=device))
    inner_model = inner_model.eval().requires_grad_(False)
    model = K.external.VDenoiser(inner_model)
    clip_model = clip.load(inner_model.clip_model, jit=False, device=device)[0]

    target_embed = clip_model.encode_text(clip.tokenize(prompt)).float()

    gc.collect()
    torch.manual_seed(seed)

    sigmas = K.sampling.get_sigmas_karras(steps, 1e-2, 160, device=device)
    x = torch.randn([4, 3, side_y, side_x], device=device) * sigmas[0]

    model_wrap = CFGDenoiser(model, weight)
    extra_args = {'clip_embed': target_embed.repeat([4, 1])}
    outs = K.sampling.sample_lms(model_wrap, x, sigmas, extra_args=extra_args, callback=callback)
    tqdm.write('Done!')
    filenames = []

    for i, out in enumerate(outs):
        filename = os.path.join(output_dir, f'out_{i}.png')
        filenames.append(filename)
        K.utils.to_pil_image(out).save(filename)

    return filenames

api/controllers/trick_controller.py
# game_controller.py
from flask import render_template,Response
import cv2
import mediapipe as mp


def trick():
    # Renderiza la plantilla 'index.html'
    return render_template('trick.html')

api/routes/audio_routes.py
from flask import render_template, Response, request
from controllers.audio_controller import upload_audio, audio
from flask import Blueprint

# Crear un Blueprint llamado 'audio_routes'
audio_routes = Blueprint('audio_routes', __name__)

@audio_routes.route('/audio')
def audio_route():
    """
    Ruta para mostrar la página de audio.
    Llama a la función 'audio' del controlador.
    """
    return audio()

@audio_routes.route('/upload-audio', methods=['POST'])
def upload_audio_route():
    """
    Ruta para manejar la carga de archivos de audio.
    Llama a la función 'upload_audio' del controlador.
    """
    # Obtener el archivo de audio y el idioma desde la solicitud
    audio_file = request.files['audio']
    lang = request.form['lang']

    # Llamar a la función de controlador para manejar la carga de audio
    return upload_audio(audio_file, lang)

api/routes/game_routes.py
from flask import render_template, Response, request
from controllers.game_controller import game,video_game
from flask import Blueprint

# Crear un Blueprint llamado 'audio_routes'
game_routes = Blueprint('game_routes', __name__)

# Ruta para la página principal
@game_routes.route('/game')
def index_game():
    # Llama a la función index del controlador principal
    return game()

@game_routes.route('/video_game')
def video_screen_game():
    """
    Ruta para transmitir el video en tiempo real.
    Llama a la función 'video_feed' del controlador.
    """
    return video_game()

api/routes/image_routes.py
# main_routes.py
from flask import render_template, Response, request
from controllers.image_controller import text_to_image, move_to_folder, image
from flask import Blueprint

# Crea un Blueprint para las rutas relacionadas con imágenes
image_routes = Blueprint('image_routes', __name__)

# Ruta para mostrar la página de imágenes
@image_routes.route('/image')
def image_route():
    return image()

# Ruta para manejar la solicitud de generación de imágenes a partir de texto
@image_routes.route('/text-to-image', methods=['POST'])
def text_to_image_route():
    # Obtén los datos del formulario enviado
    prompt = request.form['prompt']
    steps = int(request.form['steps'])
    weight = int(request.form['weight'])
    seed = int(request.form['seed'])

    # Llama a la función text_to_image con los parámetros proporcionados
    return text_to_image(prompt, steps, weight, seed)

# Ruta para servir archivos estáticos desde el directorio "public"
@image_routes.route('/public/<path:filename>')
def serve_file(filename):
    # Llama a la función move_to_folder para servir el archivo solicitado
    return move_to_folder(filename)

api/routes/video_routes.py
from flask import render_template, Response, request
from controllers.video_controller import video_feed, video
from flask import Blueprint

# Crear un Blueprint llamado 'video_routes'
video_routes = Blueprint('video_routes', __name__)

@video_routes.route('/video')
def video_route():
    """
    Ruta para mostrar la página de video.
    Llama a la función 'video' del controlador.
    """
    return video()

@video_routes.route('/video_feed')
def video_feed_route():
    """
    Ruta para transmitir el video en tiempo real.
    Llama a la función 'video_feed' del controlador.
    """
    return video_feed()

api/templates/audio.html
{% from "macros/template.html" import head,light_control,header,footer,endhead %}
{{ head() }}
{{ light_control() }}
{{ header() }}
<!-- Begin page content -->
<main class="flex-shrink-0">
    <div class="container">
        <div class="card">
            <div class="card-header">
                Inserte fichero de audio
            </div>
            <div class="card-body">
                <form id="form" action="/upload-audio" method="post" enctype="multipart/form-data" onsubmit="showLoader('form')">
                    <div class="form-input mb-3">
                        <label for="audio">Seleccionar archivo de audio</label>
                        <input type="file" id="audio" name="audio" accept="audio/*" required>
                    </div>
                    <div class="form-input mb-3">
                        <label for="lang">Seleccionar lenguaje</label>
                        <select id="lang" name="lang">
                            <option value="es">Español</option>
                            <option value="en">Inglés</option>
                            <option value="fr">Francés</option>
                            <option value="de">Alemán</option>
                        </select>
                    </div>
                    <div class="form-submit text-center">
                        <button type="submit" class="btn btn-primary">Enviar</button>
                    </div>
                </form>
                <div id="loader" class="loader d-none justify-content-center align-items-center text-center">
                    <div class="spinner-border" role="status">
                        <span class="visually-hidden">Cargando...</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{{ footer() }}
{{ endhead() }}

api/templates/audio_view.html
{% from "macros/template.html" import head,light_control,header,footer,endhead %}
{{ head() }}
{{ light_control() }}
{{ header() }}
<!-- Begin page content -->
<main class="flex-shrink-0">
    <div class="container">
        <div class="card">
            <div class="card-header">
                Resultado
            </div>
            <div class="card-body">
                <p class="card-text form-lang">{{ lang }}</p>
                <audio controls>
                    <source src="{{ audio_path }}" type="audio/mp3">
                    Tu navegador no soporta la reproducción de audio.
                </audio>
                <p class="card-text lead">{{ result }}</p>
            </div>
            <div class="text-center my-2">
                <a href="{{ url_for('audio_routes.audio_route') }}" class="btn btn-primary">Regresar</a>
            </div>
        </div>
    </div>
</main>
{{ footer() }}
{{ endhead() }}

api/templates/game.html
{% from "macros/template.html" import head,light_control,header,footer,script,endhead %}
{{ head() }}
{{ light_control() }}
{{ header() }}
<!-- Begin page content -->
<main class="flex-shrink-0">
    <div class="container">
        <div class="card">
            <div class="card-header">
                Game
            </div>
            <div class="card-body p-2">
                <p>Utiliza la barra espaciadora para hacer saltos</p>
                <canvas id="gameCanvas" width="800" height="600"></canvas>
            </div>
        </div>
        <div class="card">
            <div class="card-header">
                Video captura
            </div>
            <div class="card-body">
                <p>Levantar mano izquierda = Salta el rectangulo rojo</p>
                <p>Levantar mano derecha = Salta el rectangulo verde</p>
                <div style="max-width: 640px; overflow: hidden;">
                    <img src="{{ url_for('game_routes.video_screen_game') }}" alt="Video Stream" style="width: 640px;">
                </div>
            </div>
        </div>
    </div>
</main>
{{ footer() }}
<!-- Include the Socket.IO client library -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/3.0.4/socket.io.js"></script>

<script src="../static/js/game.js"></script>
{{ endhead() }}

api/templates/image.html
{% from "macros/template.html" import head,light_control,header,footer,endhead %}
{{ head() }}
    {{ light_control() }}
    {{ header() }}
    <!-- Begin page content -->
    <main class="flex-shrink-0">
        <div class="container">
            <div class="card">
                <div class="card-header">
                    Genera tu Personaje
                </div>
                <div class="card-body">
                    <form id="form-2" action="/text-to-image" method="post" enctype="multipart/form-data" onsubmit="showLoader('form-2')">
                        <div class="form-input mb-3">
                            <label for="inputText">Ingresa texto (máximo 255 caracteres):</label><br>
                            <textarea id="inputText" name="prompt" rows="4" cols="50" maxlength="255" oninput="updateCharacterCount()" required></textarea><br>
                            <span id="characterCount">255</span> caracteres restantes
                        </div>
                        <div class="form-input mb-3">
                            <label for="weight">Exactitud</label>
                            <input type="number" id="weight" name="weight" size="4" required>
                        </div>
                        <div class="form-input mb-3">
                            <label for="steps">Pasos</label>
                            <input type="number" id="steps" name="steps" size="4" required>
                        </div>
                        <div class="form-input mb-3">
                            <label for="seed">Seed</label>
                            <input type="number" id="seed" name="seed" size="4" required>
                        </div>
                        <div class="form-submit text-center">
                            <button type="button" class="btn btn-warning" onclick="resetForm()">Limpiar</button>
                            <button type="submit" class="btn btn-primary">Generar</button>
                        </div>
                    </form>
                    <div id="image_box" style="display:none"> </div>
                    <div id="loader" class="loader d-none justify-content-center align-items-center text-center">
                        <div class="spinner-border" role="status">
                            <span class="visually-hidden">Cargando...</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
    {{ footer() }}

<script>
    function updateCharacterCount() {
        const maxLength = 255;
        const inputText = document.getElementById('inputText');
        const characterCount = document.getElementById('characterCount');
        const remainingChars = maxLength - inputText.value.length;

        characterCount.textContent = remainingChars;
    }
    function resetForm() {
        const form1 = document.getElementById('form'); // Primer formulario
        const form2 = document.getElementById('form-2'); // Segundo formulario
        form1.reset();
        form2.reset();
        updateCharacterCount(); // Actualizar el contador después de limpiar el formulario
    }

    // Llamado inicial para actualizar el contador al cargar la página
    updateCharacterCount();
</script>
{{ endhead() }}

api/templates/image_view.html
{% from "macros/template.html" import head,light_control,header,footer,endhead %}
{{ head() }}
{{ light_control() }}
{{ header() }}
<!-- Begin page content -->
<main class="flex-shrink-0">
<div class="container">
    <div class="card">
        <div class="card-header">
            Resultado
        </div>
        <div class="card-body">
            <div class="container">
                <div class="row mb-4">
                    <div class="col-md-6">
                        <img src="../{{ image_path[0] }}" alt="Image 1" class="img-fluid">
                    </div>
                    <div class="col-md-6">
                        <img src="../{{ image_path[1] }}" alt="Image 2" class="img-fluid">
                    </div>
                </div>
                <div class="row mb-4">
                    <div class="col-md-6">
                        <img src="../{{ image_path[2] }}" alt="Image 3" class="img-fluid">
                    </div>
                    <div class="col-md-6">
                        <img src="../{{ image_path[3] }}" alt="Image 4" class="img-fluid">
                    </div>
                </div>
            </div>
        </div>

        <div class="text-center my-2">
            <a href="{{ url_for('image_routes.image_route') }}" class="btn btn-primary">Regresar</a>
        </div>
    </div>
</div>
</main>
{{ footer() }}
{{ endhead() }}

api/templates/index.html
{% from "macros/template.html" import head,light_control,header,footer,endhead %}
{{ head() }}
    {{ light_control() }}
    {{ header() }}
    <!-- Begin page content -->
    <main class="flex-shrink-0">
        <div class="container">
            <h1 class="mt-5">Bienvenidos a la API de proyectos AI</h1>
            <p class="lead">Aqui publicamos los proyectos relacionados con modelos de inteligencia artificial.</p>
            <p class="lead">Estas son algunas de las tecnologias utilizadas en los proyectos, se ha utilizado Flask como Framework de Python para consumir los modelos.</p>
            <ul>
                <li><strong>argparse:</strong> Módulo de Python para analizar argumentos de la línea de comandos.</li>
                <li><strong>clip:</strong> Librería para copiar texto al portapapeles desde el terminal.</li>
                <li><strong>k_diffusion:</strong> Herramienta externa para añadir ruido a las imagenes</li>
                <li><strong>sounddevice:</strong> Librería para acceder a dispositivos de sonido desde Python.</li>
                <li><strong>torch:</strong> PyTorch, una biblioteca de aprendizaje profundo.</li>
                <li><strong>wavfile:</strong> Módulo de SciPy para leer y escribir archivos WAV.</li>
                <li><strong>mtranslate:</strong> Paquete para traducción automática.</li>
                <li><strong>gtts:</strong> Google Text-to-Speech, una interfaz para la API de síntesis de voz de Google.</li>
                <li><strong>openai-whisper:</strong> Herramienta de OpenAI para convertir texto en audio.</li>
                <li><strong>ffmpeg-python:</strong> Una interfaz de Python para FFmpeg, una herramienta multimedia.</li>
                <li><strong>mediapipe:</strong> Biblioteca para soluciones de percepción en tiempo real.</li>
                <li><strong>pygame:</strong> Biblioteca para desarrollo de videojuegos en Python.</li>
                <li><strong>opencv-python:</strong> OpenCV, una biblioteca de visión por computadora.</li>
                <li><strong>flask-socketio:</strong> Extensión de Flask para agregar soporte de Socket.IO a una aplicación Flask.</li>
            </ul>

        </div>
    </main>
    {{ footer() }}
{{ endhead() }}

api/templates/trick.html
{% from "macros/template.html" import head,light_control,header,footer,script,endhead %}
{{ head() }}
{{ light_control() }}
{{ header() }}
<!-- Begin page content -->
<main class="flex-shrink-0">
    <div class="container">
        <div class="card">
            <div class="card-header">
                Trick
            </div>
            <div class="card-body p-2">
                <p>Caja vacia</p>
            </div>
        </div>
    </div>
</main>
{{ footer() }}
{{ endhead() }}

api/templates/video.html
{% from "macros/template.html" import head,light_control,header,footer,endhead %}
{{ head() }}
    {{ light_control() }}
    {{ header() }}
    <!-- Begin page content -->
    <main class="flex-shrink-0">
        <div class="container">
            <div class="card">
                <div class="card-header">
                    Video captura
                </div>
                <div class="card-body">
                    <p>Levantar mano derecha = Video color rojo</p>
                    <p>Levantar mano izquierda = Video color azul</p>
                    <p>dos manos arriba = Video color lila</p>
                    <div style="max-width: 640px; overflow: hidden;">
                        <img src="{{ url_for('video_routes.video_feed_route') }}" alt="Video Stream" style="width: 640px;">
                    </div>
                </div>
            </div>
        </div>
    </main>
    {{ footer() }}
{{ endhead() }}